# .github/workflows/pylint.yml

name: Pylint

on: [push]

jobs:
  lint: # Changed job name for clarity
    runs-on: ubuntu-latest
    # Removed the Python version matrix - linting once is usually enough
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python # Using a specific recent version
      uses: actions/setup-python@v5 # Use latest version of setup-python
      with:
        python-version: '3.11' # Or '3.10', '3.9', etc. - choose one

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        # Run pylint on all .py files found by git
        # Use --fail-under to make the job fail if the score is too low
        # The .pylintrc file will be automatically detected and used
        pylint --fail-under=8.0 $(git ls-files '*.py')
        # Alternatively, to fail on specific message types (Error, Warning, Convention):
        # pylint --fail-on=E,W,C $(git ls-files '*.py')
